#!/bin/bash

case ${BLOCK_BUTTON} in
   	1) bluetoothctl -- power on  > /dev/null 2>&1  ;;
	2) bluetoothctl -- connect 30:FD:38:8A:62:C8 ;;
	3) bluetoothctl -- power off > /dev/null 2>&1  ;;
esac

# 2 for connecting to speaker

BT_STAT=$(python3 ~/.config/i3blocks/scripts/aux/bluetooth_info.py)
echo -e ${BT_STAT}
