#!/bin/bash

case $BLOCK_BUTTON in
    4)  sudo light -U 5 ;;
    5)  sudo light -A 5 ;;
esac

BRIGHTNESS=$(cat /sys/class/backlight/*/brightness)
MAXBRIGHTNESS=$(cat /sys/class/backlight/*/max_brightness)

PERCENT=$(((BRIGHTNESS * 100 / MAXBRIGHTNESS + 3) / 5 * 5))

echo -e "<span font='12'>\uf835</span>  $PERCENT%"
